version: "3.9"

services:
  web:
    build:
      context: ../
      dockerfile: ./ngui/Dockerfile
      args:
        NODE_ENV: development
    environment:
      BUILD_MODE: development
    ports:
      - "4000:4000"
    depends_on:
      redis:
        condition: service_started
    restart: unless-stopped

  redis:
    image: "redis:7.0.9"
    ports:
      - "6379:6379"
    restart: unless-stopped
