services:
  web:
    build:
      args:
        - NODE_ENV=development
      context: ../
      dockerfile: ./ngui/Dockerfile
    environment:
      - BUILD_MODE=development
      - UI_BUILD_PATH=/usr/src/app/ui/dist
      - PROXY_URL=http://localhost:4000
    ports:
      - "4000:4000"
    depends_on:
      redis:
        condition: service_started
    restart: unless-stopped
