import {
  GET_ORGANIZATIONS,
  CREATE_ORGANIZATION,
  GET_DATA_SOURCES,
  GET_CURRENT_EMPLOYEE,
  GET_DATA_SOURCE,
  GET_INVITATIONS,
  GET_ORGANIZATION_FEATURES,
  GET_OPTSCALE_MODE,
  UPDATE_OPTSCALE_MODE,
  GET_ORGANIZATION_THEME_SETTINGS,
  GET_ORGANIZATION_PERSPECTIVES
} from "./restapi.queries";

export {
  GET_ORGANIZATIONS,
  CREATE_ORGANIZATION,
  GET_DATA_SOURCES,
  GET_CURRENT_EMPLOYEE,
  GET_DATA_SOURCE,
  GET_INVITATIONS,
  GET_ORGANIZATION_FEATURES,
  GET_OPTSCALE_MODE,
  UPDATE_OPTSCALE_MODE,
  GET_ORGANIZATION_THEME_SETTINGS,
  GET_ORGANIZATION_PERSPECTIVES
};
